35 color chooser
jentoobento/FileCabinet pull request #12
Opened 2020-08-11 22:39 UTC by enleiwu

Home.tsx
- Added color chooser with animation similar to icon chooser.
- Added collapseAll() to collapse all expanded sections within the modal when a new section is clicked
- Implemented selected color to renderLists()

resources/color.js
- Implemented a new color scheme (more info in color scheme ticket)

2020-08-11 22:41 UTC, enleiwu commented
Discussion: background color and font/icon color contrast--some of the looks weird

2020-08-12 19:02 UTC, jentoobento commented
The Add Icons button is stretching when Icon Color is open and vice versa, can we fix that so they don't change size when the other one is open?

2020-08-12 19:04 UTC, jentoobento commented
When I open Icon Color Chooser and click Add Icon button without choosing a color, the Icon Color Chooser should close back to normal size. Right now it's defaulting to some random color

2020-08-12 21:05 UTC, enleiwu commented
> When I open Icon Color Chooser and click Add Icon button without choosing a color, the Icon Color Chooser should close back to normal size. Right now it's defaulting to some random color

I can't replicate this. I did click Add List -> click Change List Color -> click Add Icon w/o choosing a color
result: color picker went back to the default white with Change List Color

2020-08-12 21:47 UTC, enleiwu commented
> The Add Icons button is stretching when Icon Color is open and vice versa, can we fix that so they don't change size when the other one is open?

Fixes pushed

2020-08-13 23:17 UTC, jentoobento requested changes

2020-08-13 23:17 UTC, jentoobento commented on src/screens/Home/styles.tsx
> +    borderRadius: 10,
Can we add the diagonal color like the mock up? I think it would be something like this:
```
borderLeftWidth: 50,
    borderBottomWidth: 100,
    borderLeftColor: 'transparent',
    borderBottomColor: 'color here',

2020-08-14 16:45 UTC, enleiwu commented on src/screens/Home/styles.tsx
> +    borderRadius: 10,
We can, but what's the purpose of the diagonal color though? Originally I thought it was meant to support Light Mode/Dark Mode, but if we currently don't support it, we probably shouldn't have it for now. It might be a confusing UX as the user will expect the color to come into play.

2020-08-14 17:26 UTC, jentoobento commented on src/screens/Home/styles.tsx
> +    borderRadius: 10,
It's for the color of the list and the files. The main and border colors

2020-08-20 01:43 UTC, jentoobento approved these changes

2020-08-20 01:43 UTC, jentoobento commented on src/screens/Home/Home.tsx
> +    LIST_COLORS[listColorKeys[parseInt(listColorKeys.length * Math.random())]];
I don't think you need to parse int here. Doesn't this already return a number?

2020-08-20 01:46 UTC, merged